### ISSUE TITLE
Distance / RSSI

### ISSUE THREAD

**Issue by ekkesa** [andrewjfreyer/presence#15]
Thank you for this awesome piece of work. I'm looking into rolling it out with a Pi in each room, but would like to be able to differentiate in which room a person is. I recall mentioned somewhere, you might look at the possibility of including RSSI in the JSON payload. Is this still on the cards?

**Comment by andrewjfreyer** [comment]
I would recommend against getting that many raspberry pis specifically because of the interference issue that other users have reported.  And, unfortunately, the technique I am using to detect the presence of phones  and other non-beacon devices does not capture an RSSI measurement. Frankly, RSSI measurements are only loosely correlated with distance anyhow.

**Comment by ekkesa** [comment]
Thank you for the reply - Trying to figure out a way to accurately place someone in a room and not false positives from PIRs as someone walks by. Didn't think about interference of all the Pis - Will take that into account. Appreciated!
